### PR TITLE
Add Household support for Mealie V2

### PR DESCRIPTION
**Pull request by andrew-codechimp**
# Proposed Changes

This is a draft work in progress that I'm looking for advice/review on.

To distinguish the household support (V2) I am using a call within `define_household_support` to detect api availability as version checking does not work when Nightly could be V1 or V2 

Most JSON responses now include a householdId which I'm having trouble with Mashumoro defining as optional, see `MealPlan` model for my attempt, which currently fails tests where the `mealplan_today.json` does not include the field, advise on how to handle optionals would be great, I've not found an example that works yet.

Also once the above is resolved advice on how to add my local lib into my local HA Core temporarily so I can test implementation there.

### CODE REVIEW

**Comment by joostlek** [comment]
Maybe we should create a base entity and then extend

**Comment by joostlek** [comment]
Let's ask them if we can get a better way for detecting version

**Comment by joostlek** [comment]
And maybe we should do more effort to make like a V1 submodule so we can keep supporting it

(Just also thinking out loud as I'm at F1 right now)

**Comment by andrew-codechimp** [comment]
> And maybe we should do more effort to make like a V1 submodule so we can keep supporting it
> 
> (Just also thinking out loud as I'm at F1 right now)

I was thinking of separate tests for V1 at least so we can continue support for a while but the code should work with either.

No problem, I don't expect quick answers to these things and won't be jumping on changing things so take your time, just putting this here to show the impact and we can iterate.

**Comment by joostlek** [comment]
Yea I think we should check with the mealie team if they have like a support window for Mealie V1, I also don't really feel like supporting that for an eternity

**Comment by andrew-codechimp** [comment]
Just a heads up, the HassIO AddOn for Mealie was updated yesterday.  Despite it saying v1.12.0 which is the latest prod release it has built with the V2 nightly, so the integration is now failing to setup.

I've raised an [issue](https://github.com/alexbelgium/hassio-addons/issues/1548) there to hopefully stop this in future but the damage is done and rolling back won't be an option due to DB changes.

**Comment by joostlek** [comment]
OUCH. I guess we have to make sure we fix this before the release (4 September) because 2024.8.3 is probably coming out today so we won't make that

**Comment by andrew-codechimp** [comment]
Ouch indeed, expect a lot of issues being raised for the next week, of which we just got our first!
It's just the optional householdId that's stopping my code so far from working, if you could solve that we'll be ready, just within the limits of the current Mealie versioning.

**Comment by joostlek** [comment]
Yea I'll be looking into this tonight or tomorrow. Which means we don't make 8.3 but will be included in 2024.9

**Comment by andrew-codechimp** [comment]
The Mealie Add On is now correctly using latest rather than nightly, a restore required for those that upgraded already and that's mentioned in the release but at least its reduced impact for integration users.
Bonus is the Add-On users are now on a Mealie version rather than nightly so no log warnings in future.

**Comment by joostlek** [comment]
Yea I'll also look into helping mealie get a proper nightly versioning. I want to avoid to do a trail and error. This is the first time this happens, but who knows how many more times we have such change?

**Comment by joostlek** [comment]
I think I am just going to build a check that will warn users that we will deprecate the older versions once this one is released

**Comment by andrew-codechimp** [comment]
Thanks for fixing up those optionals, obvious now I see it!
With most people seeming to be auto-updating with that HA AddOn we should be able to deprecate V1 support pretty quickly and get rid of the cludge.

**Pull request merged**
